version: '3.8' 
services:
  mern-app:
    build: .
    ports:
      - '5000:5000'
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    networks:
      - mongoCluster
  mongo1:
    image: mongo:5
    container_name: mongo1
    command: ["mongod", "--replSet", "myReplicaSet", "--bind_ip_all"]
    volumes:
      - mongo1_data:/data/db
    networks:
      - mongoCluster
    ports:
      - '27017:27017'
  mongo2:
    image: mongo:5
    container_name: mongo2
    command: ["mongod", "--replSet", "myReplicaSet", "--bind_ip_all"]
    volumes:
      - mongo2_data:/data/db
    networks:
      - mongoCluster
    ports:
      - '27018:27017'
  mongo3:
    image: mongo:5
    container_name: mongo3
    command: ["mongod", "--replSet", "myReplicaSet", "--bind_ip_all"]
    volumes:
      - mongo3_data:/data/db
    networks:
      - mongoCluster
    ports:
      - '27019:27017'
volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
networks:
  mongoCluster:
    driver: bridge
